#!/bin/bash

function installing_fonts_for_wps() {
  if [ ! -d ~/.fonts ]; then
    echo
    echo "Install Microsoft fonts for wps..."
    cp -r .fonts > ~/.fonts
  else
    check_log -s "wps fonts"
  fi
}

function installing_fonts() {
  installing_fonts_for_wps
}
