#!/bin/bash

function log() {
  echo $1
}

function check_config() {
  local ANSWER
  read -n1 -p "$2 [y/N]? " ANSWER
  echo
  if [ "$ANSWER" = "Y" -o "$ANSWER" = "y" ]; then
    eval CONFIG_$1=true
  else
    eval CONFIG_$1=false
  fi
}

function check_log() {
  local d
  for d in ${TMPS[@]};
  do
    if [ "$d" = "$2" ]; then
      return
    fi
  done

  if [ "$1" = "-i" ]; then
    TMPS=(${TMPS[@]} $2)
    echo "checked $2 installed!"
  elif [ "$1" = "-s" ]; then
    echo "checked $2 has setup!"
  fi
}

